# --- Build (Angular) ---
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
# Produce dist/spacex-launches-front/browser (según tu angular.json)
RUN npm run build --base-href="/prod/" --deploy-url="/prod/"

# --- Runtime (Nginx) ---
FROM nginx:1.27-alpine

# Usa tu config como default y elimina el HTML por defecto
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*

# Copia el build correcto (nota el /browser/)
COPY --from=builder /app/dist/spacex-launches-front/browser/ /usr/share/nginx/html/

# (Opcional) Puertos/health no son necesarios aquí; Nginx ya escucha en 80
EXPOSE 80