server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

springdoc:
  swagger-ui:
    enabled: true

aws:
  access : ${AWS_ACCESS_KEY_ID}
  secret : ${AWS_SECRET_ACCESS_KEY}


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.jpa: DEBUG
    io.github.cristhianm30.spacex-launches-back: DEBUG