server:
  port: 8080
  servlet:
    context-path: /api

spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    enabled: true
    path: /swagger
    config-url: /docs/swagger-config
    url: /docs
